version: '2.1'

services:
  help-yourself-db:
    image: mysql:latest
    hostname: help-yourself-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: "no"

  help-yourself.web:
    build: ./help-yourself.web
    hostname: help-yourself
    ports:
      - "8080:8080"
    depends_on:
      help-yourself-db:
        condition: service_healthy
    links:
      - help-yourself-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 30s
      retries: 10
    restart: "no"